
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.ArgumentType.ValueIsOption(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.Program.Main(System.String[])~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.Serialize(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.Serialize(System.String,System.Int16)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.Serialize(System.Int16)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.MjpCreatorExecute(System.String[])~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.Argument.Url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.NameNorm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.NameAbbrivNorm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.AllowedValues")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.OtherNamesForbiddenWithThis")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.OtherNamesForbiddenWithoutThis")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.OtherNamesRequiredWithThis")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.OtherNamesRequiredWithoutThis")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.ArgumentType.Values")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.ArgumentType.ParseArgumentList(System.String[],System.Collections.Generic.IList{MediaCenter.SharedComponents.ArgumentType},System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.ArgumentType.ParseArgumentList(System.String[],System.Collections.Generic.IList{MediaCenter.SharedComponents.ArgumentType},System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.ArgumentExtensionType.ContainsName(System.Collections.Generic.IEnumerable{MediaCenter.SharedComponents.ArgumentType},System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.ArgumentExtensionType.ContainsSpecifiedName(System.Collections.Generic.IEnumerable{MediaCenter.SharedComponents.ArgumentType},System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.ArgumentExtensionType.GetByName(System.Collections.Generic.IEnumerable{MediaCenter.SharedComponents.ArgumentType},System.String)~MediaCenter.SharedComponents.ArgumentType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.CreateMjpCreator(System.String,System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.Collections.Generic.IEnumerable{System.String},System.String,System.String)~MediaCenter.SharedComponents.MjpCreator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.MjpCreatorExecute(System.String[])~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.MjpCreatorExecute(System.String[])~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.MjpCreator.Serialize(System.Int16)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.MjpFileEntry.Actions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.MjpPackage.Url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MediaCenter.SharedComponents.MjpPackageFile.FileEntries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MediaCenter.SharedComponents.Program.Main(System.String[])~System.Int32")]
